### ISSUE TITLE
Suggestion: Create a standalone example in the webpage

### ISSUE THREAD

**Issue by hahsan1** [Qepanna/goFlux#14]
It may be helpful to have a separate bare bones example section where it runs through each step (e.g., import, goFlux, best.flux, plotting) for just a single data set.

**Comment by Qepanna** [comment]
@hahsan1 I created a new page on the webpage with two downloadable zip folders containing either a simple workflow or a bit more complex workflow.
https://qepanna.quarto.pub/goflux/example.html
